config/routes.rb
# -*- coding: utf-8 -*-
Profile::Application.routes.draw do
  resources :settings

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  match 'welcome' => 'projects#index'

  match '~koji', :controller => "pages", :action => "show", :project_id => "~koji", :id => "プロフィール"
  match '~koji/mizuno.html', :controller => "pages", :action => "show", :project_id => "~koji", :id => "プロフィール"
  match '~koji(/:controller(/:id(/:action)))', :project_id => "~koji", :action => "show"

  resources :sessions
  resources :users do
    member do
      get 'edit_roles'
      put 'update_roles'
    end
  end

  resources :projects do
    resources :pages do
      resources :sections
    end
    resources :pictures, :only => :destroy
    resources :papers, :only => [:password,:download,:destroy] do
      member do
        get 'password'
        post 'download'
      end
    end
  end

  root :to => "projects#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_create :set_role
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  ROLES = %w(god admin mini_admin member)

  def role?( role ); roles.include? role.to_s end
  def role_symbols; roles.map(&:to_sym) end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  def set_role; self.roles = ["member"] if self.roles.empty? end
  
  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.order('username asc')
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => t('notice.thank_you_for_signing_up')
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => updated(:profile)
    else
      render :action => 'edit'
    end
  end

  def destroy
    redirect_to users_path
  end
  
  def edit_roles
  end

  def update_roles
    @user.roles = params[:user][:roles] unless params[:user].nil?
    if @user.save
      redirect_to users_path, :notice => updated_p(@user.username, :role)
    else
      render :action => 'edit_roles'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= semantic_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit (@user.new_record? ? t(:sign_up) : update(:profile)), :class => :submit %>
<% end %>

app/views/users/edit.html.erb
<% title edit(:profile) %>

<%= render 'form' %>

app/views/users/edit_roles.html.erb
<% title edit_p(:role) %>

<%= semantic_form_for @user, :url => update_roles_user_path(@user), :method => :put do |f| %>
  <% for role in User::ROLES[1,User::ROLES.length-1] %>
    <p>
      <label>
        <%= check_box_tag "user[roles][]", role, @user.roles.include?( role ) %>
        <%= t(role).humanize %>
      </label>
    </p>
  <% end %>
<%= f.submit update_p(:role), :class => :small_submit %>
<% end %>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td>
        <%= link_to t(:show), user if can? :show, user %>
        <%= link_to t(:edit), edit_user_path(user) if can? :edit, user %>
        <%= link_to pl(:role), edit_roles_user_path(user) if can? :edit_roles, user %>
        <%= link_to t(:del), user, :confirm => sure?, :method => :delete if can? :destroy, user %>
      </td>
    </tr>
  <% end %>
</ul>

app/views/users/new.html.erb
<% title t(:sign_up) %>

<%= render 'form' %>