config/routes.rb
# -*- coding: utf-8 -*-
Profile::Application.routes.draw do
  resources :settings

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  match 'welcome' => 'projects#index'

  match '~koji', :controller => "pages", :action => "show", :project_id => "~koji", :id => "プロフィール"
  match '~koji/mizuno.html', :controller => "pages", :action => "show", :project_id => "~koji", :id => "プロフィール"
  match '~koji(/:controller(/:id(/:action)))', :project_id => "~koji", :action => "show"

  resources :sessions
  resources :users do
    member do
      get 'edit_roles'
      put 'update_roles'
    end
  end

  resources :projects do
    resources :pages do
      resources :sections
    end
    resources :pictures, :only => :destroy
    resources :papers, :only => [:password,:download,:destroy] do
      member do
        get 'password'
        post 'download'
      end
    end
  end

  root :to => "projects#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:index,:show], Project
    can :show, Page
    can :create, User
    can [:password,:download], Paper

    if user
      if user.role?(:member)
        can :update, User, :id => user.id
        can :show, User
      end
      if user.role?(:mini_admin)
        can [:show,:index,:update], User
        can :index, Page
        can [:show,:index,:admin], Project
        can [:show,:index], Setting
      end
      if user.role? :admin
        can [:show,:index,:update,:destroy,:edit_roles,:update_roles], User
        can [:show,:index,:create,:update,:destroy], [Project,Page]
        can :admin, Project
        can [:destroy], [Paper, Picture]
        can [:show,:index,:new,:create,:edit,:update,:destroy], Setting
      end
      if user.role? :god
        can :manage, :all
      end
    end
  end
end

app/models/list_section.rb
class ListSection < Section
end

app/models/list_subsection.rb
class ListSubsection < Subsection
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :project
  has_many :sections
  accepts_nested_attributes_for :sections, :allow_destroy => true
  
  attr_accessible :name, :menu, :sections_attributes

  validates :project_id, :presence => true
  validates :name, :presence => true, :uniqueness => {:scope => :project_id}
  validates :pos, :uniqueness => {:scope => :project_id}
  validates :menu, :presence => true, :uniqueness => {:scope => :project_id}
  
  def to_param; name end
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  belongs_to :project

  attr_accessor :title, :password
  mount_uploader :file, PaperUploader
  before_save :prepare_password

  validates :name, :presence => true, :uniqueness => {:scope => :project_id}
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  def extension; file.url.split('.').last end
  def listing; "#{name} (#{file_url ? file.file.filename : ""})" end

  def authenticate(pass)
    return password_hash == encrypt_password(pass)
  end
  
  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private
    
    def prepare_password
      unless password.blank?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = encrypt_password(password)
      end
    end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :project

  mount_uploader :image, ImageUploader

  validates :name, :presence => true, :uniqueness => {:scope => :project_id}

  def listing; "#{name} (#{image_url ? image.file.filename : ""})" end
end

app/models/profile_section.rb
class ProfileSection < Section
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :pages
  has_many :pictures
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  has_many :papers
  accepts_nested_attributes_for :papers, :allow_destroy => true
  
  attr_accessible :name, :title, :subtitle, :pictures_attributes, :papers_attributes

  validates :name, :presence => true, :uniqueness => true

  def to_param; name end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :page
  has_many :subsections, :dependent => :destroy
  accepts_nested_attributes_for :subsections, :allow_destroy => true

  mount_uploader :image, ImageUploader
  
  attr_accessible :title, :subtitle, :type, :subsections_attributes, :image

  validates :page_id, :presence => true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :name, :prefix
end

app/models/subsection.rb
class Subsection < ActiveRecord::Base
  belongs_to :section

  attr_accessible :type, :content, :col1, :col2, :col3
  
  def col1; content && content.split('#')[0] end
  def col2; content && content.split('#')[1] end
  def col3; content && content.split('#')[2] end

  def col1=(s); self.content = s end
  def col2=(s); self.content += "##{s}" end
  def col3=(s); self.content += "##{s}" end
end

app/models/table_section.rb
class TableSection < Section
end

app/models/text_section.rb
class TextSection < Section
end

app/models/text_subsection.rb
class TextSubsection < Subsection
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_create :set_role
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  ROLES = %w(god admin mini_admin member)

  def role?( role ); roles.include? role.to_s end
  def role_symbols; roles.map(&:to_sym) end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  def set_role; self.roles = ["member"] if self.roles.empty? end
  
  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sections/_form.html.erb
<%= form_for [@project,@page,@section] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </p>
  <p>
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/sections/_list_section.html.erb
<div id="list_section" class="<%= first ? "first" : "" %>">
<h3><%= section.title %></h3>
<h4><%= section.subtitle %></h4>
<ul>
  <% section.subsections.each do |subsection| %>
    <li><%= clean subsection.content %></li>
  <% end %>
</ul>
</div>

app/views/sections/_profile_section.html.erb
<div id="profile_section" class="<%= first ? "first" : "" %>">

<img src="<%= prefixed_url(section.image_url) %>" />
<div id="table">
  <h3><%= section.title %></h3>
  <h4><%= section.subtitle %></h4>
  <% section.subsections.each do |subsection| %>
  <div id="row">
    <% unless subsection.col1.blank? %>
      <div id="col1"><%= clean subsection.col1 %></div>
    <% end %>
    <% unless subsection.col2.blank? %>
      <div id="col2"><%= clean subsection.col2 %></div>
    <% end %>
    <% unless subsection.col3.blank? %>
      <% if subsection.col2.blank? %>
        <div id="col3_wide"><%= clean subsection.col3 %></div>
      <% else %>
        <div id="col3"><%= clean subsection.col3 %></div>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>
<div class="clear"></div>
</div>

app/views/sections/_table_section.html.erb
<div id="table_section" class="<%= first ? "first" : "" %>">
<h3><%= section.title %></h3>
<h4><%= section.subtitle %></h4>

<% section.subsections.each do |subsection| %>
  <div id="row">
    <% unless subsection.col1.blank? %>
      <div id="col1"><%= clean subsection.col1 %></div>
    <% end %>
    <% unless subsection.col2.blank? %>
      <div id="col2"><%= clean subsection.col2 %></div>
    <% end %>
    <% unless subsection.col3.blank? %>
      <% if subsection.col2.blank? %>
        <div id="col3_wide"><%= clean subsection.col3 %></div>
      <% else %>
        <div id="col3"><%= clean subsection.col3 %></div>
      <% end %>
    <% end %>
  </div>
<% end %>
</div>

app/views/sections/_text_section.html.erb
<div id="text_section" class="<%= first ? "first" : "" %>">
<h3><%= section.title %></h3>
<h4><%= section.subtitle %></h4>
<% section.subsections.each do |subsection| %>
<p class="<%= section.subsections.first == subsection ? 'first' : '' %>">
  <%= clean subsection.content %>
</p>
<% end %>
</div>

app/views/sections/edit.html.erb
<% title "Edit Section" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @section %> |
  <%= link_to "View All", sections_path %>
</p>

app/views/sections/index.html.erb
<% title "Sections" %>

<table>
  <tr>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Type</th>
  </tr>
  <% for section in @sections %>
    <tr>
      <td><%= section.title %></td>
      <td><%= section.subtitle %></td>
      <td><%= section.type %></td>
      <td><%= link_to "Show", [@project,@page,section] %></td>
      <td><%= link_to "Edit", edit_project_page_section_path(@project,@page,section) %></td>
      <td><%= link_to "Destroy", [@project,@page,section], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Section", new_project_page_section_path(@project,@page,section) %></p>

app/views/sections/new.html.erb
<% title "New Section" %>

<%= render 'form' %>

<p><%= link_to "Back to List", project_page_sections_path(@project,@page) %></p>

app/views/sections/show.html.erb
<% title "Section" %>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>
<p>
  <strong>Subtitle:</strong>
  <%= @section.subtitle %>
</p>
<p>
  <strong>Type:</strong>
  <%= @section.type %>
</p>

<p>
  <%= link_to "Edit", edit_section_path(@section) %> |
  <%= link_to "Destroy", @section, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", sections_path %>
</p>